[package]
name = "audit-logging"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
platform = ["hmac", "ed25519-dalek", "reqwest"]

[dependencies]
thiserror.workspace = true
serde = { workspace = true }
serde_json.workspace = true
tracing.workspace = true
chrono = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }

# Cryptography for hash chains and tamper evidence
sha2 = "0.10"
hex = "0.4"

# Input validation for log injection prevention
input-validation = { path = "../input-validation" }

# Unix-specific dependencies for disk space monitoring
[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["fs"] }

# Optional platform mode dependencies
hmac = { version = "0.12", optional = true }
ed25519-dalek = { version = "2.0", optional = true }
reqwest = { version = "0.11", optional = true, features = ["json"] }

[dev-dependencies]
tempfile = "3.8"
proptest.workspace = true
