[package]
name = "audit-logging"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
serde = { workspace = true }
serde_json.workspace = true
tracing.workspace = true
chrono = { workspace = true }
