# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "daemon-lifecycle"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "daemon_lifecycle"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["process", "time", "fs"] }
anyhow = "1.0"
observability-narration-core = { path = "../narration-core" }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
