# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "daemon-lifecycle"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "daemon_lifecycle"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["process", "time", "fs"] }
anyhow = "1.0"
reqwest = { version = "0.12", features = ["json"] }  # TEAM-259: For health checks
serde = { version = "1.0", features = ["derive"] }  # TEAM-259: For CRUD operations
serde_json = "1.0"  # TEAM-259: For CRUD operations
observability-narration-core = { path = "../narration-core" }
auto-update = { path = "../auto-update" }  # TEAM-259: For auto-updating daemons
timeout-enforcer = { path = "../timeout-enforcer" }  # TEAM-276: For timeout wrapper
nix = { version = "0.29", features = ["signal"] }  # TEAM-276: For SIGTERM/SIGKILL
stdext = "0.3"  # TEAM-312: Required for n!() macro (function_name!())

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
