[package]
name = "observability-narration-macros"
version = "0.0.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"
authors = ["rbee contributors"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

# TEAM-328: No dev-dependencies needed - macro is tested via integration in daemon-lifecycle
