[package]
name = "worker-http-bdd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["bdd-cucumber"]
bdd-cucumber = []

[dependencies]
anyhow = { workspace = true }
cucumber = "0.20"
tokio = { workspace = true }
worker-http = { path = ".." }
axum = "0.7"
tower = "0.4"
hyper = { workspace = true }

[[bin]]
name = "bdd-runner"
path = "src/main.rs"
