[package]
name = "worker-http-bdd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["bdd-cucumber"]
bdd-cucumber = []

[dependencies]
anyhow = "1.0"
cucumber = "0.20"
tokio = { version = "1.0", features = ["full"] }
worker-http = { path = ".." }
worker-common = { path = "../../worker-common" }
axum = "0.7"
tower = "0.4"
hyper = "1.0"
async-trait = "0.1"
serde_json = "1.0"

[[bin]]
name = "bdd-runner"
path = "src/main.rs"
