[package]
name = "deadline-propagation"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
http.workspace = true
tracing.workspace = true
