[package]
name = "pool-registry"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
serde = { workspace = true }
tracing.workspace = true
