# TEAM-135: Created for happy flow requirements

[package]
name = "queen-rbee-scheduler"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "queen_rbee_scheduler"
path = "src/lib.rs"

[dependencies]
# TEAM-164: Pure business logic dependencies only (no HTTP)
tokio = { workspace = true }
anyhow = { workspace = true }
observability-narration-core = { path = "../../99_shared_crates/narration-core" }
job-registry = { path = "../../99_shared_crates/job-registry" }
queen-rbee-hive-catalog = { path = "../hive-catalog" }

[dev-dependencies]
# Add dev dependencies as needed
