# TEAM-270: Worker contract types and API specification

[package]
name = "worker-contract"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "worker_contract"
path = "src/lib.rs"

[dependencies]
# Shared contract types
shared-contract = { path = "../shared-contract" }  # TEAM-284: Use shared types

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"
