[package]
name = "timeout-enforcer-macros"
version = "0.1.0"
edition = "2021"

# Created by: TEAM-330
# Purpose: Ergonomic attribute macro for timeout enforcement
# Wraps async functions with TimeoutEnforcer automatically

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
