# TEAM-135: Created by TEAM-135 (scaffolding)
# NOTE: Moved to shared-crates because BOTH workers AND hives send heartbeats

[package]
name = "rbee-heartbeat"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "rbee_heartbeat"
path = "src/lib.rs"

[dependencies]
tokio = { version = "1", features = ["time", "macros"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"  # TEAM-159: For JSON parsing in receivers
chrono = "0.4"
tracing = "0.1"
thiserror = "1.0"  # TEAM-159: For error types in traits
async-trait = "0.1"  # TEAM-159: For async trait methods
observability-narration-core = { path = "../narration-core" }  # TEAM-159: For narration in queen receiver

[dev-dependencies]
serde_json = "1"
