[package]
name = "worker-tokenizer"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Tokenization (BPE, HuggingFace) for llama-orch workers"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tokenizers = "0.15"
worker-gguf = { path = "../worker-gguf" }

[dev-dependencies]
tempfile = "3.8"
