packages:
  - consumers/llama-orch-utils
  - consumers/.examples/*
  - consumers/llama-orch-sdk/ts
  - frontend/bin/commercial
  - frontend/libs/frontend-tooling
  - frontend/reference/v0

onlyBuiltDependencies:
  - esbuild
  - workerd
