packages:
  - frontend/apps/commercial
  - frontend/apps/user-docs
  - frontend/apps/web-ui
  - frontend/packages/rbee-ui
  - frontend/packages/rbee-sdk
  - frontend/packages/tailwind-config
  - frontend/reference/v0

onlyBuiltDependencies:
  - esbuild
  - workerd
