packages:
  - consumers/rbee-utils
  - consumers/.examples/*
  - consumers/rbee-sdk/ts
  - frontend/apps/commercial
  - frontend/apps/user-docs
  - frontend/packages/frontend-tooling
  - frontend/packages/rbee-ui
  - frontend/reference/v0

onlyBuiltDependencies:
  - esbuild
  - workerd
