packages:
  - frontend/apps/commercial
  - frontend/apps/user-docs
  - frontend/apps/web-ui
  - frontend/packages/rbee-ui
  - frontend/packages/rbee-sdk
  - frontend/packages/rbee-react
  - frontend/packages/tailwind-config
  - frontend/reference/v0
  - bin/00_rbee_keeper/ui
  
onlyBuiltDependencies:
  - esbuild
  - workerd
