packages:
  - frontend/apps/commercial
  - frontend/apps/user-docs
  - frontend/packages/rbee-ui
  - frontend/packages/tailwind-config
  - frontend/packages/typescript-config
  - frontend/packages/eslint-config
  - frontend/packages/vite-config
  - frontend/packages/shared-config
  - frontend/packages/narration-client
  - frontend/packages/iframe-bridge
  - frontend/packages/dev-utils
  - bin/00_rbee_keeper/ui
  - bin/10_queen_rbee/ui/app
  - bin/10_queen_rbee/ui/packages/queen-rbee-sdk
  - bin/10_queen_rbee/ui/packages/queen-rbee-react
  - bin/20_rbee_hive/ui/app
  - bin/20_rbee_hive/ui/packages/rbee-hive-sdk
  - bin/20_rbee_hive/ui/packages/rbee-hive-react
  - bin/30_llm_worker_rbee/ui/app
  - bin/30_llm_worker_rbee/ui/packages/llm-worker-sdk
  - bin/30_llm_worker_rbee/ui/packages/llm-worker-react

onlyBuiltDependencies:
  - esbuild
  - workerd
