packages:
  - consumers/llama-orch-utils
  - consumers/.examples/*
  - consumers/llama-orch-sdk/ts
  - frontend/bin/commercial
  - frontend/bin/d3-sim-frontend
  - frontend/libs/frontend-tooling
  - frontend/reference/v0
