packages:
  - consumers/rbee-utils
  - consumers/.examples/*
  - consumers/rbee-sdk/ts
  - frontend/bin/commercial
  - frontend/bin/user-docs
  - frontend/libs/frontend-tooling
  - frontend/libs/rbee-ui
  - frontend/reference/v0

onlyBuiltDependencies:
  - esbuild
  - workerd
