[package]
name = "observability-narration-core"
version = "0.0.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"
authors = ["llama-orch contributors"]
autobenches = false
autodocs = false

[lib]
name = "observability_narration_core"
path = "src/lib.rs"

[dependencies]
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
regex = { workspace = true }
uuid = { workspace = true }
opentelemetry = { version = "0.21", optional = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
criterion = "0.5"
serial_test = "3.0"

[[bench]]
name = "narration_benchmarks"
harness = false

[features]
default = []
trace-enabled = []  # Enable trace macros (dev/debug builds only)
debug-enabled = []  # Enable debug-level narration
cute-mode = []      # Enable cute narration fields
otel = ["opentelemetry"]
test-support = []  # Enables test capture adapter in non-test builds
production = []     # Production profile (all tracing disabled)
