[package]
name = "candle_ln_test"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
candle-core = { path = "../../../../reference/candle/candle-core" }
candle-nn = { path = "../../../../reference/candle/candle-nn" }
