[package]
name = "ssh-contract"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "SSH-related contracts for rbee ecosystem"
authors.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
# TEAM-316: Optional Tauri support for TypeScript generation
specta = { version = "=2.0.0-rc.22", optional = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1.0"

[features]
# TEAM-316: Enable Tauri/Specta derives for TypeScript generation
tauri = ["specta"]

[lints]
workspace = true
