[package]
name = "worker-orcd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "worker-orcd"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

# Shared crates
gpu-info = { path = "../shared-crates/gpu-info" }

# Worker crates
vram-policy = { path = "../worker-orcd-crates/vram-policy" }
model-loader = { path = "../worker-orcd-crates/model-loader" }
worker-api = { path = "../worker-orcd-crates/api" }
worker-error-handler = { path = "../worker-orcd-crates/error-handler" }
