[package]
name = "worker-orcd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[dependencies]
worker-gguf = { path = "../worker-crates/worker-gguf" }
worker-tokenizer = { path = "../worker-crates/worker-tokenizer" }
worker-models = { path = "../worker-crates/worker-models" }
worker-common = { path = "../worker-crates/worker-common" }
worker-http = { path = "../worker-crates/worker-http" }
tokio = { workspace = true }
anyhow.workspace = true
async-trait = "0.1"
tracing.workspace = true
tracing-subscriber.workspace = true
axum = { workspace = true }
tower = { version = "0.5", features = ["util"] }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
observability-narration-core = { path = "../shared-crates/narration-core", features = ["axum", "cute-mode"] }
half = "2.4"
# [TEAM PICASSO 2025-10-07T15:36Z] Numeric parity logging
lazy_static = { version = "1.4", optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
toml = "0.8"
uuid = { version = "1.0", features = ["v4"] }
tempfile = "3.8"
chrono = "0.4"
rand = "0.8"

[build-dependencies]
cmake = "0.1"
toml = "0.8"

[features]
default = []
cuda = []  # Enable CUDA support (requires NVIDIA GPU + CUDA toolkit)
# [TEAM PICASSO 2025-10-07T15:38Z] Numeric parity logging feature
# Enables append-only JSONL logging for comparing with llama.cpp ground truth
# Usage: cargo test --features cuda,orch_logging ...
# Env vars: ORCH_LOG_FILE, ORCH_LOG_TEAM, ORCH_LOG_VALUES
# See: investigation-teams/PARITY_COMPARISON_SPEC.md
orch_logging = ["lazy_static"]

[[bin]]
name = "worker-orcd"
path = "src/main.rs"


