[package]
name = "worker-orcd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[features]
default = []
cuda = []  # Enable CUDA support (requires NVIDIA GPU + CUDA toolkit)

[[bin]]
name = "worker-orcd"
path = "src/main.rs"

[[test]]
name = "tokenizer_conformance_qwen"
path = "tests/tokenizer_conformance_qwen.rs"

[[test]]
name = "qwen_integration"
path = "tests/qwen_integration.rs"

[[test]]
name = "phi3_integration"
path = "tests/phi3_integration.rs"

[[test]]
name = "adapter_integration"
path = "tests/adapter_integration.rs"

[[test]]
name = "llama_integration_suite"
path = "tests/llama_integration_suite.rs"

[[test]]
name = "reproducibility_validation"
path = "tests/reproducibility_validation.rs"

[[test]]
name = "vram_pressure_tests"
path = "tests/vram_pressure_tests.rs"

[dependencies]
tokio = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
axum = { workspace = true }
tower = { version = "0.5", features = ["util"] }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
observability-narration-core = { path = "../shared-crates/narration-core", features = ["axum"] }
tokenizers = "0.15"

[dev-dependencies]
serial_test = "3.0"
uuid = { version = "1.0", features = ["v4"] }
tempfile = "3.8"

[build-dependencies]
cmake = "0.1"
toml = "0.8"
