[package]
name = "worker-orcd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[features]
default = []
cuda = []  # Enable CUDA support (requires NVIDIA GPU + CUDA toolkit)

[[bin]]
name = "worker-orcd"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
axum = { workspace = true }
tower = { version = "0.5", features = ["util"] }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
observability-narration-core = { path = "../shared-crates/narration-core", features = ["axum"] }

[dev-dependencies]
serial_test = "3.0"

[build-dependencies]
cmake = "0.1"
toml = "0.8"
