[package]
name = "worker-orcd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[features]
default = []
cuda = []  # Enable CUDA support (requires NVIDIA GPU + CUDA toolkit)

[[bin]]
name = "worker-orcd"
path = "src/main.rs"


