[package]
name = "worker-orcd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
build = "build.rs"

[features]
default = []
cuda = []  # Enable CUDA support (requires NVIDIA GPU + CUDA toolkit)

[[bin]]
name = "worker-orcd"
path = "src/main.rs"

[[test]]
name = "tokenizer_conformance_qwen"
path = "tests/tokenizer_conformance_qwen.rs"

[[test]]
name = "qwen_integration"
path = "tests/qwen_integration.rs"

[[test]]
name = "phi3_integration"
path = "tests/phi3_integration.rs"

[[test]]
name = "adapter_integration"
path = "tests/adapter_integration.rs"

[[test]]
name = "llama_integration_suite"
path = "tests/llama_integration_suite.rs"

[[test]]
name = "reproducibility_validation"
path = "tests/reproducibility_validation.rs"

[[test]]
name = "vram_pressure_tests"
path = "tests/vram_pressure_tests.rs"

[[test]]
name = "gpt_integration"
path = "tests/gpt_integration.rs"

[[test]]
name = "adapter_factory_integration"
path = "tests/adapter_factory_integration.rs"

[[test]]
name = "all_models_integration"
path = "tests/all_models_integration.rs"

[[test]]
name = "oom_recovery"
path = "tests/oom_recovery.rs"

[[test]]
name = "utf8_edge_cases"
path = "tests/utf8_edge_cases.rs"

[[test]]
name = "cancellation_integration"
path = "tests/cancellation_integration.rs"

[[test]]
name = "correlation_id_middleware_test"
path = "tests/correlation_id_middleware_test.rs"

[[test]]
name = "phi3_tokenizer_conformance"
path = "tests/phi3_tokenizer_conformance.rs"

[[bench]]
name = "performance_baseline"
harness = false

[dependencies]
tokio = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
axum = { workspace = true }
tower = { version = "0.5", features = ["util"] }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
reqwest = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
observability-narration-core = { path = "../shared-crates/narration-core", features = ["axum", "cute-mode"] }
tokenizers = "0.15"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
toml = "0.8"
uuid = { version = "1.0", features = ["v4"] }
tempfile = "3.8"

[build-dependencies]
cmake = "0.1"
toml = "0.8"
