[package]
name = "observability-narration-core"
version = "0.0.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"
authors = ["rbee contributors"]
autobenches = false
autodocs = false

[lib]
name = "observability_narration_core"
path = "src/lib.rs"

[dependencies]
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
regex = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
once_cell = "1.19"
opentelemetry = { version = "0.21", optional = true }
axum = { workspace = true, optional = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
criterion = "0.5"
serial_test = "3.0"
tokio = { version = "1", features = ["macros", "rt"] }
tower = { version = "0.5", features = ["util"] }

[[bench]]
name = "narration_benchmarks"
harness = false

[features]
default = []
trace-enabled = []  # Enable trace macros (dev/debug builds only)
debug-enabled = []  # Enable debug-level narration
cute-mode = []      # Enable cute narration fields
otel = ["opentelemetry"]
axum = ["dep:axum"]
test-support = []  # Enables test capture adapter in non-test builds
production = []     # Production profile (all tracing disabled)
