[package]
name = "observability-narration-core"
version = "0.5.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"
authors = ["rbee contributors"]
autobenches = false
autodocs = false

[lib]
name = "observability_narration_core"
path = "src/lib.rs"

[dependencies]
tracing = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
regex = { workspace = true }
uuid = { workspace = true }
tokio = { workspace = true, features = ["sync", "process", "io-util"] } # TEAM-300: Added process, io-util for ProcessNarrationCapture
once_cell = "1.19"
stdext = "0.3" # TEAM-312: For function_name!() macro
opentelemetry = { version = "0.21", optional = true }
axum = { workspace = true, optional = true }
anyhow = { workspace = true } # TEAM-300: For process_capture Result types
reqwest = { workspace = true, optional = true } # TEAM-303: For fake binaries HTTP forwarding
futures = { version = "0.3", optional = true } # TEAM-303: For fake binaries SSE streaming

[dev-dependencies]
tracing-subscriber = { workspace = true }
criterion = "0.5"
serial_test = "3.0"
tokio = { version = "1", features = ["macros", "rt", "net"] } # TEAM-303: Added net for TcpListener
tower = { version = "0.5", features = ["util"] }
job-server = { path = "../job-server" } # TEAM-302: For test harness
job-client = { path = "../job-client" } # TEAM-303: For E2E tests
operations-contract = { path = "../../97_contracts/operations-contract" } # TEAM-303: For E2E tests
futures = "0.3" # TEAM-303: For SSE streaming

[[bench]]
name = "narration_benchmarks"
harness = false

# TEAM-303: Test binaries for E2E integration tests
[[bin]]
name = "fake-queen-rbee"
path = "tests/bin/fake_queen.rs"
required-features = ["axum"]

[[bin]]
name = "fake-rbee-hive"
path = "tests/bin/fake_hive.rs"
required-features = ["axum"]

[[bin]]
name = "fake-worker"
path = "tests/bin/fake_worker.rs"

[features]
default = []
trace-enabled = []  # Enable trace macros (dev/debug builds only)
debug-enabled = []  # Enable debug-level narration
cute-mode = []      # Enable cute narration fields
otel = ["opentelemetry"]
axum = ["dep:axum", "dep:reqwest", "dep:futures"]  # TEAM-303: Include deps for test binaries
test-support = []  # Enables test capture adapter in non-test builds
production = []     # Production profile (all tracing disabled)
