# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "queen-rbee-ssh-client"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "queen_rbee_ssh_client"
path = "src/lib.rs"

[dependencies]
# TEAM-260: Command-based SSH using system ssh/scp tools
tokio = { version = "1", features = ["process", "time"] }
anyhow = "1.0"
observability-narration-core = { path = "../../99_shared_crates/narration-core" }

[dev-dependencies]
# Add dev dependencies as needed
