[package]
name = "health-poll"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
tokio = { version = "1.0", features = ["time"] }
tracing = "0.1"
