[package]
name = "health-poll"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
observability-narration-core = { path = "../../99_shared_crates/narration-core" }
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
stdext = "0.3"
tokio = { version = "1.0", features = ["time"] }
tracing = "0.1"
