[package]
name = "llorch-ctl"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# TEAM-024 CLARIFICATION:
# This is the CLI tool for OPERATORS (humans)
# Binary name: `llorch` (SSH-based remote control)
# NOT the orchestrator daemon!
# The orchestrator HTTP daemon is: `orchestratord` (separate binary, M2)

[[bin]]
name = "llorch"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
colored = "2.0"
ssh2 = { workspace = true }
indicatif = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
