[package]
name = "worker-adapters-mock"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[lib]
name = "worker_adapters_mock"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
