# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-hive-worker-lifecycle"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "rbee_hive_worker_lifecycle"
path = "src/lib.rs"

[dependencies]
# Shared lifecycle management
daemon-lifecycle = { path = "../../99_shared_crates/daemon-lifecycle" }

# Add other dependencies as needed

[dev-dependencies]
# Add dev dependencies as needed
