[package]
name = "proof-bundle-bdd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["bdd-cucumber"]
bdd-cucumber = []

[dependencies]
anyhow = { workspace = true }
cucumber = { version = "0.20", features = ["macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
proof_bundle = { path = "..", package = "proof-bundle" }
tempfile = "3"

[[bin]]
name = "bdd-runner"
path = "src/main.rs"
