[package]
name = "xtask"
version = "0.0.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"
autobenches = false
autotests = false
autodocs = false

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
walkdir = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
openapiv3 = { workspace = true }
contracts-config-schema = { path = "../contracts/config-schema" }
provisioners-engine-provisioner = { path = "../libs/provisioners/engine-provisioner" }
auth-min = { path = "../libs/auth-min" }
