# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "queen-rbee-hive-registry"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "queen_rbee_hive_registry"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
rbee-heartbeat = { path = "../../99_shared_crates/heartbeat" }

[dev-dependencies]
