# TEAM-135: Created for happy flow requirements

[package]
name = "sse-relay"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "sse_relay"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
tokio-stream = "0.1"
axum = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
# Add dev dependencies as needed
