# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "queen-rbee-hive-lifecycle"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "queen_rbee_hive_lifecycle"
path = "src/lib.rs"

[dependencies]
# TEAM-164: Pure business logic dependencies only (no HTTP)
anyhow = "1.0"
tokio = { version = "1", features = ["process"] }
chrono = "0.4"
observability-narration-core = { path = "../../99_shared_crates/narration-core" }
queen-rbee-hive-catalog = { path = "../hive-catalog" }

[dev-dependencies]
# Add dev dependencies as needed
