// Auto-generated by ts_export (llama-orch-utils). Do not edit.

export type ReadRequest = { paths: Array<string>, as_text: boolean, encoding: string | null, };

export type FileBlob = { path: string, content: string | null, bytes: Array<number> | null, };

export type ReadResponse = { files: Array<FileBlob>, };

export type WriteIn = { path: string, text: string, create_dirs: boolean, };

export type WriteOut = { path: string, bytes_written: number, };

export type Source = { "Text": string } | { "Lines": Array<string> } | { "File": string };

export type MessageIn = { role: string, source: Source, dedent: boolean, };

export type Message = { role: string, content: string, };

export type ThreadItem = { role: string, source: Source, dedent: boolean, };

export type ThreadIn = { items: Array<ThreadItem>, };

export type ThreadOut = { messages: Array<Message>, };

export type ModelRef = { model_id: string, engine_id: string | null, pool_hint: string | null, };

export type Params = { temperature: number | null, top_p: number | null, max_tokens: number | null, seed: bigint | null, };

export type SdkMsg = { role: string, content: string, };

export type Choice = { text: string, };

export type Usage = { prompt_tokens: number | null, completion_tokens: number | null, };

export type InvokeResult = { choices: Array<Choice>, usage: Usage | null, };

export type InvokeIn = { messages: Array<SdkMsg>, model: ModelRef, params: Params, };

export type InvokeOut = { result: InvokeResult, };

