# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-keeper-queen-lifecycle-bdd"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "bdd-runner"
path = "src/main.rs"

[dependencies]
# Parent crate
rbee-keeper-queen-lifecycle = { path = ".." }

# BDD testing
cucumber = "0.20"
tokio = { version = "1", features = ["full"] }
anyhow = "1"

# HTTP client for health checks in tests
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"

[dev-dependencies]
# Add dev dependencies as needed
