# TEAM-135: Created by TEAM-135 (BDD scaffolding)

[package]
name = "rbee-keeper-bdd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["bdd-cucumber"]
bdd-cucumber = []

[dependencies]
anyhow = { workspace = true }
cucumber = { version = "0.20", features = ["macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.11", features = ["json"] }
futures = { workspace = true }
rbee-keeper = { path = ".." }

[[bin]]
name = "bdd-runner"
path = "src/main.rs"
