[package]
name = "keeper-config-contract"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Keeper configuration contract for rbee ecosystem"
authors.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.8"

[lints]
workspace = true
