[package]
name = "job-registry"
version = "0.1.0"
edition = "2021"
authors = ["TEAM-154"]
description = "Shared job registry for dual-call inference pattern across worker, queen, and hive"
license = "GPL-3.0-or-later"

[dependencies]
# Core dependencies
tokio = { version = "1", features = ["sync", "rt"] }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"  # TEAM-186: For payload storage

# TEAM-186: For execute_and_stream helper
futures = "0.3"  # Stream utilities
observability-narration-core = { path = "../narration-core" }  # Narration events
anyhow = "1.0"  # Error handling

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
base64 = "0.21"
