use anyhow::Result;
use std::io::Write;

pub const TEXT_HEADER: &str = "# AUTOGENERATED: Proof Bundle\n";

pub fn ensure_text_header_write(mut w: impl Write, body: &str) -> Result<()> {
    if !body.starts_with(TEXT_HEADER) {
        w.write_all(TEXT_HEADER.as_bytes())?;
    }
    w.write_all(body.as_bytes())?;
    Ok(())
}

pub fn ndjson_meta_value() -> serde_json::Value {
    serde_json::json!({
        "_meta": "proof_bundle",
        "_note": "autogenerated"
    })
}
