[package]
name = "queen-rbee"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# Orchestrator daemon (HTTP server)
# Binary name: `queen-rbee`
# Purpose: Job scheduling, admission control, worker registry, SSE relay
# Protocol: HTTP (listens on port 8080)
# Milestone: M1+

[[bin]]
name = "queen-rbee"
path = "src/main.rs"

[dependencies]
# HTTP server
axum = "0.8"
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors"] }

# Async runtime
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time", "signal", "fs"] }
futures = "0.3"

# HTTP client (for calling workers)
reqwest = { version = "0.12", features = ["json", "stream"] }

# TEAM-030: Removed SQLite - using in-memory storage for ephemeral mode
# Database (SQLite for state persistence)
# sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# CLI
clap = { version = "4.5", features = ["derive"] }

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }

# UUID generation
uuid = { version = "1.0", features = ["v4", "serde"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
tempfile = "3.0"
wiremock = "0.6"
