# Deterministic finance engine v2 — single canonical input
# How to run:
#   cd .business/financieelplan_NL_nl
#   command make templates validate run
# or directly:
#   ./fp run config.yaml --out ./out --months 12 --scenario base --vat-period monthly

# Schema version of this config format (increment if structure changes)
schema_version: 1
# Bedrijfsmeta: gebruikt voor labels/kalender, niet voor berekeningen behalve start_maand
bedrijf:
  # Vrije naam/label voor rapportage
  naam: Onbekend
  # Rechtsvorm bepaalt indicatieve belasting (IB=eenmanszaak/VOF of BV)
  rechtsvorm: eenmanszaak
  # Start van de horizon (YYYY-MM). Depreciaties/leningen beginnen vanaf deze maand
  start_maand: 2025-10
  # Valuta-label voor formatting (EUR)
  valuta: EUR
# Lengte van de planhorizon in maanden (bijv. 12..36)
horizon_maanden: 12
# Scenario-keuze beïnvloedt slechts interne branching; templates tonen de naam
scenario: base
# BTW-aangiftefrequentie: monthly of quarterly. Bepaalt timing van btw-afdracht in cashflow
vat_period: monthly
# BTW/Belastingen. Bepaalt btw-over omzet/inkoop en indicatieve inkomstenbelasting
btw:
  # Standaard btw-tarief voor je producten/diensten (in %)
  btw_pct: 21
  # Btw-model: 'omzet_enkel' of 'omzet_minus_simple_kosten' (eenvoudig aftrekbaar)
  model: omzet_enkel
  # Kleineondernemersregeling (KOR): true -> btw-afdracht 0
  kor: false
  # Volledig btw-vrijgesteld (bijv. sommige zorg/onderwijs). true -> btw-afdracht 0
  btw_vrij: false
  # IB-specifiek: MKB-vrijstelling in % toegepast op resultaat v/b vóór indicatieve heffing
  mkb_vrijstelling_pct: 0
##
## Omzetstromen — Credits-first (Public Tap)
##
# Elke stream heeft: naam, prijs (per eenheid), volume_pm (eenheden/mnd), var_kosten_per_eenheid (COGS), btw, dso_dagen
# Credits-first: eenheid = 1M tokens; prijs = EUR per 1M tokens; volume_pm = M tokens verkocht per maand
omzetstromen:
- naam: Public Tap (credits)
  # EUR per 1M tokens (zie .002-draft/ADR-XXX-public-tap-pricing.md: baseline €1.20)
  prijs: 1.20
  # Volume in M tokens per maand. Kortere arrays worden automatisch aangevuld met de laatst bekende waarde
  volume_pm:
  - 2000   # 2,000M tokens (~€2,400 omzet)
  - 3000
  - 4000
  - 6000
  - 8000
  - 9000
  - 10000
  - 11000
  - 12000
  - 12000
  - 12000
  - 12000
  # Variabele kosten (COGS) per eenheid. Voor credits-first: infra-kosten per 1M tokens
  var_kosten_per_eenheid: 0.85   # schatting; verfijn na GPU/host benchmarks
  # Btw tarief voor deze stroom (indien anders dan default)
  btw_pct: 21
  # Days Sales Outstanding per stream. Prepaid credits -> 0 (cash upfront)
  dso_dagen: 0                   # prepaid credits → DSO ≈ 0
##
## OPEX vast per maand — vaste lasten (geen COGS)
##  personeel: bruto_pm per medewerker (excl. werkgeverslasten voor eenvoud)
##  marketing/software/huisvesting/overig: vaste bedragen per maand
opex_vast_pm:
  personeel: []                  # voorbeeld: [{ rol: Founder, bruto_pm: 3000 }]
  marketing: 500.0               # advertenties, content, tools
  software: 200.0                # SaaS, domains (infra-usage staat bij COGS)
  huisvesting: 800.0             # huur/werkplek (0 als volledig remote)
  overig: 1500.0                 # verzekeringen, administratie, overige
##
## Investeringen (CAPEX) — lineaire afschrijving per maand vanaf start_maand
##  Credits-first: doorgaans weinig CAPEX (huur/GPU als COGS). Houd dit leeg of klein
investeringen:
- omschrijving: Laptop
  bedrag: 2500.0
  levensduur_mnd: 36
  start_maand: 2025-10
##
## Financiering — eigen inbreng en leningen (annuïteiten, grace optioneel)
##  Let op: leningen drukken DSCR/runway. Bij prepaid credits kan je mogelijk zonder lening starten
financiering:
  eigen_inbreng: 0.0
  leningen:
  - verstrekker: Qredits
    hoofdsom: 30000.0
    rente_nominaal_jr: 9.0
    looptijd_mnd: 48
    grace_mnd: 6
    alleen_rente_in_grace: true
##
## Werkkapitaal — timing van kasstromen
##  dso_dagen: debiteuren (dagen). Prepaid credits -> 0
##  dpo_dagen: crediteuren (dagen). Bijv. 14
##  dio_dagen: voorraad (niet van toepassing: 0)
##  vooruitbetaald_pm: vooruitbetaalde kosten (maandelijks)
##  deferred_revenue_pm: uitgestelde omzet (maandelijks)
werkkapitaal:
  dso_dagen: 0
  dpo_dagen: 14
  dio_dagen: 0
  vooruitbetaald_pm: 0
  deferred_revenue_pm: 0
##
## Overige aannames
assumpties:
  # Voor NPV/analyses (enkel rapportage); core-model gebruikt lineaire reeksen
  discount_rate_pct: 10.0
  # Aanbevolen minimale kasbuffer (rapportage/waarschuwing in liquiditeit)
  kas_buffer_norm: 2500
