[package]
name = "worker-gguf"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "GGUF file format parser for llama-orch workers"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
byteorder = "1.5"
half = "2.4"

[dev-dependencies]
proptest = "1.0"
tempfile = "3.0"
