# rbee-sdk
#
# TEAM-286: Rust SDK that compiles to WASM for browser/Node.js usage

[package]
name = "queen-rbee-sdk"
version = "0.1.0"
edition = "2021"
authors = ["rbee Team"]
license = "GPL-3.0-or-later"

# Not part of workspace - standalone WASM package
[workspace]
description = "Rust SDK for rbee that compiles to WASM for browser/Node.js usage"
repository = "https://github.com/veighnsche/rbee"
homepage = "https://github.com/veighnsche/rbee/tree/main/consumers/rbee-sdk"
keywords = ["rbee", "llm", "wasm", "inference", "ai"]
categories = ["wasm", "api-bindings", "web-programming"]
readme = "README.md"

[lib]
crate-type = ["cdylib", "rlib"]  # cdylib = WASM, rlib = for tests

[dependencies]
# ============================================================================
# EXISTING SHARED CRATES (REUSE!)
# ============================================================================

# TEAM-286: Reuse job-client for all HTTP + SSE logic
job-client = { path = "../../../../99_shared_crates/job-client" }

# TEAM-286: Reuse operations-contract for all operation types
operations-contract = { path = "../../../../97_contracts/operations-contract" }

# TEAM-381: Enable wasm features for TypeScript type generation
# hive-contract is a pure contract crate (types only, no runtime deps)
hive-contract = { path = "../../../../97_contracts/hive-contract", features = ["wasm"] }


# ============================================================================
# WASM DEPENDENCIES
# ============================================================================

# TEAM-286: Core WASM bindings
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"

# TEAM-286: Serde for JS ↔ Rust conversion
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"

# TEAM-286: JavaScript types
js-sys = "0.3"

# TEAM-286: Web APIs
web-sys = { version = "0.3", features = [
    "Request",
    "RequestInit",
    "RequestMode",
    "Response",
    "Headers",
    "Window",
    "EventSource",
    "MessageEvent",
    "EventTarget",
    "ErrorEvent",
    "ReadableStream",
    "console", # For logging
] }

# TEAM-286: Async runtime (required for WASM)
tokio = { version = "1", features = ["sync"], default-features = false }

# TEAM-286: HTTP client (WASM-compatible)
reqwest = { version = "0.12", default-features = false, features = ["json", "stream"] }
futures-util = "0.3"
wasm-streams = "0.4"

# TEAM-286: Error handling
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
# TEAM-286: Optimize for small WASM size
opt-level = "z"           # Optimize for size
lto = true                # Link-time optimization
codegen-units = 1         # Better optimization
panic = "abort"           # Smaller binary
strip = true              # Strip symbols

[profile.release.package."*"]
opt-level = "z"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
