[package]
name = "model-catalog"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
authors = ["llama-orch contributors"]
description = "Model catalog: resolve/verify/cache and lifecycle for llama-orch"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
walkdir = { workspace = true }
regex = { workspace = true }
ureq = { version = "2", default-features = false, features = ["tls", "json"] }

[dev-dependencies]
insta = { workspace = true }
tempfile = "3"

[lib]
path = "src/lib.rs"
