# TEAM-135: Created by TEAM-135 (scaffolding)
# TEAM-151: Updated with CLI dependencies for migration

[package]
name = "rbee-keeper"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
# TEAM-294: Default to GUI binary for Tauri
default-run = "rbee-keeper-gui"

# TEAM-293: Support both CLI and GUI modes
[lib]
name = "rbee_keeper"
path = "src/lib.rs"

[[bin]]
name = "rbee-keeper"
path = "src/main.rs"

[[bin]]
name = "rbee-keeper-gui"
path = "src/tauri_main.rs"

[dependencies]
# CLI parsing
clap = { version = "4", features = ["derive"] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# HTTP client (for health checks)
reqwest = { version = "0.11", features = ["json", "stream"] }

# TEAM-155: SSE streaming dependencies
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Configuration
toml = "0.8"
dirs = "5.0"

# Error handling
anyhow = "1.0"

# TEAM-155: Narration for observability
observability-narration-core = { path = "../99_shared_crates/narration-core" }
observability-narration-macros = { path = "../99_shared_crates/narration-macros" } # TEAM-309: Proc macros
stdext = "0.3"  # TEAM-312: Required for n!() macro (function_name!())

# TEAM-309: Tracing subscriber for CLI narration visibility
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

# TEAM-152: Queen lifecycle management (consolidated)
# TEAM-185: Consolidated queen-lifecycle crate dependencies directly into rbee-keeper
daemon-lifecycle = { path = "../99_shared_crates/daemon-lifecycle" }
timeout-enforcer = { path = "../99_shared_crates/timeout-enforcer" }
operations-contract = { path = "../97_contracts/operations-contract" }  # TEAM-186/284: Operations contract
# TEAM-290: DELETED rbee-config dependency (file-based config deprecated)
job-client = { path = "../99_shared_crates/job-client" }  # TEAM-259: Shared job submission client
queen-lifecycle = { path = "../05_rbee_keeper_crates/queen-lifecycle" }  # TEAM-259: Queen lifecycle management
hive-lifecycle = { path = "../05_rbee_keeper_crates/hive-lifecycle" }  # TEAM-290: Hive lifecycle management (SSH)
ssh-config = { path = "../05_rbee_keeper_crates/ssh-config" }  # TEAM-294: SSH config parser + local
keeper-config-contract = { path = "../97_contracts/keeper-config-contract" }  # TEAM-315: Keeper configuration contract

# TEAM-293/294: Tauri v2 dependencies for GUI
# TEAM-297: Using tauri-specta v2.0.0-rc.21 for Tauri v2 support
tauri = { version = "2", features = [] }
specta = { version = "=2.0.0-rc.22" }
tauri-specta = { version = "=2.0.0-rc.21", features = ["derive", "typescript"] }
specta-typescript = "=0.0.9"

[build-dependencies]
# TEAM-293/294: Tauri v2 build dependencies
tauri-build = { version = "2", features = [] }

[dev-dependencies]
# Add dev dependencies as needed
