# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-keeper"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "rbee-keeper"
path = "src/main.rs"

[lib]
name = "rbee_keeper"
path = "src/lib.rs"

[dependencies]
# Add dependencies as needed

[dev-dependencies]
# Add dev dependencies as needed
