# TEAM-135: Created by TEAM-135 (scaffolding)
# TEAM-151: Updated with CLI dependencies for migration

[package]
name = "rbee-keeper"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "rbee-keeper"
path = "src/main.rs"

[dependencies]
# CLI parsing
clap = { version = "4", features = ["derive"] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# HTTP client (for health checks)
reqwest = { version = "0.11", features = ["json", "stream"] }

# TEAM-155: SSE streaming dependencies
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Configuration
toml = "0.8"
dirs = "5.0"

# Error handling
anyhow = "1.0"

# TEAM-155: Narration for observability
observability-narration-core = { path = "../99_shared_crates/narration-core" }

# TEAM-152: Queen lifecycle management (consolidated)
# TEAM-185: Consolidated queen-lifecycle crate dependencies directly into rbee-keeper
daemon-lifecycle = { path = "../99_shared_crates/daemon-lifecycle" }
timeout-enforcer = { path = "../99_shared_crates/timeout-enforcer" }

[dev-dependencies]
# Add dev dependencies as needed
