# TEAM-135: Created by TEAM-135 (scaffolding)
# TEAM-151: Updated with CLI dependencies for migration

[package]
name = "rbee-keeper"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "rbee-keeper"
path = "src/main.rs"

[dependencies]
# CLI parsing
clap = { version = "4", features = ["derive"] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# HTTP client (for health checks)
reqwest = { version = "0.11", features = ["json"] }

# Error handling
anyhow = "1.0"

# TEAM-152: Queen lifecycle management
rbee-keeper-queen-lifecycle = { path = "../05_rbee_keeper_crates/queen-lifecycle" }

# TODO: Add when commands crate is ready
# rbee-keeper-commands = { path = "../05_rbee_keeper_crates/commands" }

[dev-dependencies]
# Add dev dependencies as needed
