# TEAM-270: Worker contract types and API specification

[package]
name = "worker-contract"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "worker_contract"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
serde_json = "1.0"
