[package]
name = "vram-residency"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true
hmac.workspace = true
subtle.workspace = true
hkdf.workspace = true
gpu-info = { path = "../../shared-crates/gpu-info" }

[dev-dependencies]
