[package]
name = "vram-residency"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true

[dev-dependencies]
gpu-info = { path = "../../shared-crates/gpu-info" }
