# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-hive"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "rbee-hive"
path = "src/main.rs"

[lib]
name = "rbee_hive"
path = "src/lib.rs"

[dependencies]
# HTTP framework
# TEAM-189: Added HTTP server with /health endpoint
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# CLI
clap = { version = "4", features = ["derive"] }

# Error handling
anyhow = "1.0"

# TEAM-190: Heartbeat functionality
rbee-heartbeat = { path = "../99_shared_crates/heartbeat" }
observability-narration-core = { path = "../99_shared_crates/narration-core" }

# TEAM-205: Device detection for capabilities endpoint
rbee-hive-device-detection = { path = "../25_rbee_hive_crates/device-detection" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
# Add dev dependencies as needed
