# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-hive"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "rbee-hive"
path = "src/main.rs"

[lib]
name = "rbee_hive"
path = "src/lib.rs"

[dependencies]
# HTTP framework
# TEAM-189: Added HTTP server with /health endpoint
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# CLI
clap = { version = "4", features = ["derive"] }

# Error handling
anyhow = "1.0"
tracing = "0.1"  # TEAM-284: For heartbeat logging

# TEAM-284: Hive contract types (includes heartbeat)
hive-contract = { path = "../97_contracts/hive-contract" }
reqwest = { workspace = true }  # TEAM-285: For sending heartbeats to queen
observability-narration-core = { path = "../99_shared_crates/narration-core" }
observability-narration-macros = { path = "../99_shared_crates/narration-macros" }  # TEAM-313: For n!() macro in hive_check
stdext = "0.3"  # TEAM-313: Required for n!() macro (function_name!())

# TEAM-205: Device detection for capabilities endpoint
rbee-hive-device-detection = { path = "../25_rbee_hive_crates/device-detection" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# TEAM-261: Job server pattern (mirrors queen-rbee)
job-server = { path = "../99_shared_crates/job-server" }
operations-contract = { path = "../97_contracts/operations-contract" }  # TEAM-284: Renamed from rbee-operations
futures = "0.3"
async-stream = "0.3"

# TEAM-268: Model catalog for model management
rbee-hive-model-catalog = { path = "../25_rbee_hive_crates/model-catalog" }

# TEAM-361: Worker telemetry (GPU, model detection, cgroup monitoring)
rbee-hive-monitor = { path = "../25_rbee_hive_crates/monitor" }

# TEAM-334: Use daemon-lifecycle directly (worker-lifecycle removed)
# TEAM-358: RULE ZERO - lifecycle-local ALWAYS monitors (platform-specific)
#   - lifecycle-local: For installing/building/running workers (with monitoring)
lifecycle-local = { path = "../96_lifecycle/lifecycle-local" }

# TEAM-272: Random port allocation
rand = "0.8"

# TEAM-273: Shared artifact catalog abstraction
rbee-hive-artifact-catalog = { path = "../25_rbee_hive_crates/artifact-catalog" }

# TEAM-274: Worker catalog for binary management
rbee-hive-worker-catalog = { path = "../25_rbee_hive_crates/worker-catalog" }

# TEAM-366: URL validation for heartbeat edge cases
url = "2.5"

# TEAM-334: For process management (Unix only)
[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["signal"] }

[dev-dependencies]
# TEAM-364: Telemetry testing infrastructure
tokio = { workspace = true, features = ["full", "test-util"] }
hive-contract = { path = "../97_contracts/hive-contract" }
serde_json = "1.0"
