[package]
name = "rbee-hive"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# Local pool management CLI/daemon
# Binary name: `rbee-hive`
# Runs ON the pool machine (not remote)
# Called by `rbee` via SSH for remote operations

[lib]
name = "rbee_hive"
path = "src/lib.rs"

[[bin]]
name = "rbee-hive"
path = "src/main.rs"

[dependencies]
hive-core = { path = "../shared-crates/hive-core" }
model-catalog = { path = "../shared-crates/model-catalog" }  # TEAM-029: Model catalog (SQLite - persistent)
gpu-info = { path = "../shared-crates/gpu-info" }  # TEAM-052: Backend detection
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
thiserror = { workspace = true }
colored = "2.0"
serde_json = "1.0"
hostname = "0.4"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"  # TEAM-029: For home directory detection
# TEAM-022: nix removed - replaced with sysinfo for cross-platform process management
# TEAM-113: nix re-added for signal handling (SIGTERM/SIGKILL) in force-kill logic
nix = { version = "0.27", features = ["signal", "process"] }
daemonize = { workspace = true }
indicatif = { workspace = true }
sysinfo = { workspace = true }
# TEAM-026: HTTP daemon dependencies
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors"] }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
# TEAM-027: HTTP client for health checks and worker shutdown
reqwest = { workspace = true, features = ["json"] }
# TEAM-114: Random for restart jitter
rand = "0.8"
# TEAM-034: SSE streaming support
async-stream = "0.3"
futures = { workspace = true }

# TEAM-159: Heartbeat consolidation
rbee-heartbeat = { path = "../99_shared_crates/heartbeat" }
async-trait = "0.1"

# TEAM-102: Security shared crates
auth-min = { path = "../shared-crates/auth-min" }
secrets-management = { path = "../shared-crates/secrets-management" }
input-validation = { path = "../shared-crates/input-validation" }

# TEAM-104: Observability shared crates
audit-logging = { path = "../shared-crates/audit-logging" }
deadline-propagation = { path = "../shared-crates/deadline-propagation" }

# TEAM-104: Prometheus metrics
prometheus = "0.13"
lazy_static = "1.4"
