[package]
name = "rbees-pool"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# Local pool management CLI
# Binary name: `rbees-pool`
# Runs ON the pool machine (not remote)
# Called by `rbees` via SSH for remote operations

[[bin]]
name = "rbees-pool"
path = "src/main.rs"

[dependencies]
pool-core = { path = "../shared-crates/pool-core" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
colored = "2.0"
serde_json = "1.0"
hostname = "0.4"
chrono = { version = "0.4", features = ["serde"] }
# TEAM-022: nix removed - replaced with sysinfo for cross-platform process management
daemonize = { workspace = true }
indicatif = { workspace = true }
sysinfo = { workspace = true }
