[package]
name = "rbee-keeper"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# Orchestrator CLI for operators (humans)
# Binary name: `rbee` (SSH-based remote control)
# NOT the orchestrator daemon!
# The orchestrator HTTP daemon is: `queen-rbee` (separate binary, M1+)

[[bin]]
name = "rbee"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
colored = "2.0"
ssh2 = { workspace = true }
indicatif = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
