[package]
name = "rbee-keeper"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# Orchestrator CLI for operators (humans)
# Binary name: `rbee` (SSH-based remote control)
# NOT the orchestrator daemon!
# The orchestrator HTTP daemon is: `queen-rbee` (separate binary, M1+)

[[bin]]
name = "rbee"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
colored = "2.0"
ssh2 = { workspace = true }
indicatif = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
# TEAM-027: HTTP client for pool manager communication
reqwest = { workspace = true, features = ["json", "stream"] }
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
dirs = "5.0"
# TEAM-030: Removed worker-registry dependency (ephemeral mode doesn't need persistence)
# TEAM-036: Added for installation system
toml = "0.8"
hostname = "0.4"
# TEAM-084: Added tracing for logging
tracing = "0.1"
