[package]
name = "retry-policy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tokio = { workspace = true }
tracing.workspace = true
