[package]
name = "lifecycle-local"
version = "0.1.0"
edition = "2021"

[features]
# TEAM-338: RULE ZERO FIX - Optional tauri feature for specta::Type on DaemonStatus
# TEAM-379: Enable tauri feature on lifecycle-shared for DaemonStatus specta::Type
tauri = ["dep:specta", "lifecycle-shared/tauri"]

[dependencies]
# TEAM-367: Shared types and utilities
lifecycle-shared = { path = "../lifecycle-shared" }

# TEAM-338: RULE ZERO FIX - Optional specta dependency for Tauri bindings (use RC version)
specta = { version = "2.0.0-rc", optional = true }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
observability-narration-core = { path = "../../99_shared_crates/narration-core" }
observability-narration-macros = { path = "../../99_shared_crates/narration-macros" } # TEAM-330: #[with_job_id] macro
# TEAM-330: Removed daemon-lifecycle dependency - now self-contained
timeout-enforcer = { path = "../../99_shared_crates/timeout-enforcer" } # TEAM-330: Timeout enforcement
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false } # TEAM-330: HTTP client
health-poll = { path = "../health-poll" } # TEAM-358: Health polling utility
stdext = "0.3" # TEAM-330: Required for n!() macro (function_name!())
regex = "1" # TEAM-330: Required by ProcessNarrationCapture
once_cell = "1" # TEAM-330: Required by ProcessNarrationCapture
serde = { version = "1.0", features = ["derive"] } # TEAM-330: For types serialization
serde_json = "1.0" # TEAM-330: For types metadata
whoami = "1.5" # TEAM-331: For localhost detection

# TEAM-358: Process monitoring (RULE ZERO - always monitor)
# Uses existing rbee-hive-monitor crate (cross-platform)
rbee-hive-monitor = { path = "../../25_rbee_hive_crates/monitor" }

[dev-dependencies]
tokio-test = "0.4"
