# TEAM-280: Declarative daemon synchronization for hives and workers
# Moved from queen-rbee/package_manager to shared crate

[package]
name = "daemon-sync"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
# Core
anyhow = "1.0"
tokio = { workspace = true, features = ["full"] }
futures = "0.3"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Internal dependencies
observability-narration-core = { path = "../narration-core" }
queen-rbee-ssh-client = { path = "../../15_queen_rbee_crates/ssh-client" }
rbee-config = { path = "../rbee-config" }

# Utilities
shellexpand = "3.1"

[lib]
name = "daemon_sync"
path = "src/lib.rs"
