[package]
name = "jobs-contract"
version = "0.1.0"
edition = "2021"
authors = ["TEAM-305", "TEAM-312"]
description = "Job registry contract for breaking circular dependency"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
tokio = { workspace = true, features = ["sync"] }
serde_json = { workspace = true }
chrono = "0.4"
