[package]
name = "timeout-enforcer"
version = "0.1.0"
edition = "2021"

# Created by: TEAM-163
# Purpose: Hard timeout enforcement with visual countdown feedback
# Prevents hanging operations across the entire codebase

[dependencies]
tokio = { version = "1.41", features = ["time", "macros", "rt"] }
anyhow = "1.0"
atty = "0.2" # TEAM-164: TTY detection to auto-disable countdown when stderr is captured
observability-narration-core = { path = "../narration-core" } # TEAM-197: Narration v0.5.0
indicatif = "0.17" # TEAM-197: Progress bar for timeout visualization

[dev-dependencies]
tokio = { version = "1.41", features = ["full"] }
