[package]
name = "rbee-hive"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# Local pool management CLI/daemon
# Binary name: `rbee-hive`
# Runs ON the pool machine (not remote)
# Called by `rbee` via SSH for remote operations

[[bin]]
name = "rbee-hive"
path = "src/main.rs"

[dependencies]
hive-core = { path = "../shared-crates/hive-core" }
model-catalog = { path = "../shared-crates/model-catalog" }  # TEAM-029: Model catalog (SQLite - persistent)
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
thiserror = { workspace = true }
colored = "2.0"
serde_json = "1.0"
hostname = "0.4"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"  # TEAM-029: For home directory detection
# TEAM-022: nix removed - replaced with sysinfo for cross-platform process management
daemonize = { workspace = true }
indicatif = { workspace = true }
sysinfo = { workspace = true }
# TEAM-026: HTTP daemon dependencies
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace", "cors"] }
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true, features = ["v4"] }
# TEAM-027: HTTP client for health checks and worker shutdown
reqwest = { workspace = true, features = ["json"] }
