# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-hive"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "rbee-hive"
path = "src/main.rs"

[lib]
name = "rbee_hive"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }

[dev-dependencies]
# Add dev dependencies as needed
