[package]
name = "pool-managerd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "pool-managerd"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
which = "7.0"
provisioners-engine-provisioner = { path = "../../libs/provisioners/engine-provisioner" }

[dev-dependencies]
tempfile = "3"
