[package]
name = "pool-managerd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "pool-managerd"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
which = "7.0"
provisioners-engine-provisioner = { path = "../../libs/provisioners/engine-provisioner" }
axum = { workspace = true }
tokio = { workspace = true }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["trace", "cors"] }

[dev-dependencies]
tempfile = "3"
reqwest = { workspace = true }
