# TEAM-135: Created for happy flow requirements

[package]
name = "rbee-keeper-polling"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "rbee_keeper_polling"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
rbee-http-client = { path = "../../99_shared_crates/rbee-http-client" }

[dev-dependencies]
# Add dev dependencies as needed
