# TEAM-135: Created by TEAM-135 (scaffolding)
# TEAM-262: Renamed from hive-registry to worker-registry

[package]
name = "queen-rbee-worker-registry"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "queen_rbee_worker_registry"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
# TEAM-270/284: Worker contract types (includes heartbeat)
worker-contract = { path = "../../97_contracts/worker-contract" }
# TEAM-285: Generic heartbeat registry
heartbeat-registry = { path = "../../99_shared_crates/heartbeat-registry" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
