[package]
name = "daemon-contract"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
description = "Generic daemon lifecycle contracts for rbee ecosystem"
authors.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
serde_json = "1.0"

[lints]
workspace = true
