[package]
name = "gpu-info"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[features]
default = []
cuda-runtime = []  # Enable CUDA runtime API detection (requires CUDA)

[dependencies]
thiserror.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
which = "7.0"

[dev-dependencies]
tempfile = "3.8"
proptest = "1.0"
