# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "worker-rbee-http-server"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "worker_rbee_http_server"
path = "src/lib.rs"

[dependencies]
# Add dependencies as needed (likely axum, tokio)

[dev-dependencies]
# Add dev dependencies as needed
