# TEAM-135: Created by TEAM-135 (BDD scaffolding)

[package]
name = "queen-rbee-bdd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["bdd-cucumber"]
bdd-cucumber = []

[dependencies]
anyhow = { workspace = true }
cucumber = { version = "0.20", features = ["macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = { workspace = true }
tempfile = "3.0"
chrono = "0.4"  # TEAM-158: For timestamp handling
queen-rbee = { path = ".." }
queen-rbee-hive-catalog = { path = "../../15_queen_rbee_crates/hive-catalog" }
rbee-heartbeat = { path = "../../99_shared_crates/heartbeat" }  # TEAM-158: For heartbeat types
wiremock = "0.6"  # TEAM-159: HTTP mocking for device detection tests
serde_json = "1.0"  # TEAM-159: For building mock responses
reqwest = { version = "0.12", features = ["json"] }  # TEAM-159: HTTP client for tests
async-trait = "0.1"  # TEAM-159: For DeviceDetector trait impl

[[bin]]
name = "bdd-runner"
path = "src/main.rs"
