# TEAM-135: Created by TEAM-135 (BDD scaffolding)

[package]
name = "queen-rbee-bdd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["bdd-cucumber"]
bdd-cucumber = []

[dependencies]
anyhow = { workspace = true }
cucumber = { version = "0.20", features = ["macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = { workspace = true }
tempfile = "3.0"
chrono = "0.4"  # TEAM-158: For timestamp handling
queen-rbee = { path = ".." }
queen-rbee-hive-catalog = { path = "../../15_queen_rbee_crates/hive-catalog" }
rbee-heartbeat = { path = "../../99_shared_crates/heartbeat" }  # TEAM-158: For heartbeat types

[[bin]]
name = "bdd-runner"
path = "src/main.rs"
