[package]
name = "lifecycle-shared"
version = "0.1.0"
edition = "2021"

[features]
# TEAM-367: RULE ZERO - Optional tauri feature for specta::Type on DaemonStatus
tauri = ["dep:specta"]

[dependencies]
# TEAM-367: RULE ZERO - Optional specta dependency for Tauri bindings (use RC version)
specta = { version = "2.0.0-rc", optional = true }
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
observability-narration-core = { path = "../../99_shared_crates/narration-core" }
observability-narration-macros = { path = "../../99_shared_crates/narration-macros" }
timeout-enforcer = { path = "../../99_shared_crates/timeout-enforcer" }
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
stdext = "0.3" # Required for n!() macro (function_name!())
regex = "1" # Required by ProcessNarrationCapture
once_cell = "1" # Required by ProcessNarrationCapture
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
tokio-test = "0.4"
