# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-hive-monitor"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "rbee_hive_monitor"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
tokio = { workspace = true, features = ["process", "fs"] }  # TEAM-359: For async process spawning

[dev-dependencies]
# TEAM-364: Telemetry testing infrastructure
tokio = { workspace = true, features = ["full", "test-util", "time"] }
rbee-hive-monitor = { path = "." }
