[package]
name = "rbee-openai-adapter"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
description = "OpenAI-compatible API adapter for rbee queen"

[dependencies]
# HTTP server
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }

# Async runtime
tokio = { version = "1", features = ["full"] }

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Error handling
anyhow = "1"
thiserror = "1"

# Internal dependencies
rbee-operations = { path = "../../../99_shared_crates/rbee-operations" }
observability-narration-core = { path = "../../../99_shared_crates/observability-narration-core" }

# Logging
tracing = "0.1"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
