[package]
name = "worker-orcd-bdd"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "worker-bdd"
path = "src/main.rs"

[dependencies]
cucumber = "0.20"
tokio = { workspace = true }
anyhow.workspace = true
