// @generated by xtask regen-openapi (control plane). Do not edit.
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Engine {
    Llamacpp,
    Vllm,
    Tgi,
    Triton,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DrainRequest {
    pub deadline_ms: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReloadRequest {
    pub new_model_ref: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PoolHealth {
    pub live: Option<bool>,
    pub ready: Option<bool>,
    pub draining: Option<bool>,
    pub metrics: Option<serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReplicaSet {
    pub id: String,
    pub engine: Engine,
    pub load: Option<f64>,
    pub slots_total: Option<i32>,
    pub slots_free: Option<i32>,
    pub slo: Option<serde_json::Value>,
}
