# TEAM-135: Created by TEAM-135 (scaffolding)
# TEAM-151: Updated with HTTP server dependencies

[package]
name = "queen-rbee"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "queen-rbee"
path = "src/main.rs"

[dependencies]
# HTTP framework
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# Serialization (for http/types.rs)
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# CLI parsing
clap = { version = "4", features = ["derive"] }

# Narration for observability
observability-narration-core = { path = "../99_shared_crates/narration-core" }

# Error handling
anyhow = "1.0"

# TODO: Add when registries are migrated
# beehive_registry (for http/routes.rs, http/beehives.rs, etc.)
# worker_registry (for http/routes.rs, http/workers.rs, etc.)
# audit_logging (for http/routes.rs AppState)
# input_validation (for http/beehives.rs, http/inference.rs)

[dev-dependencies]
# Add dev dependencies as needed
