# TEAM-135: Created by TEAM-135 (scaffolding)
# TEAM-151: Updated with HTTP server dependencies

[package]
name = "queen-rbee"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"
build = "build.rs"

[[bin]]
name = "queen-rbee"
path = "src/main.rs"

[dependencies]
# HTTP framework
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-http = { version = "0.6", features = ["cors", "fs"] } # TEAM-288: CORS support for web UI, TEAM-293: Static file serving
reqwest = { version = "0.12", features = ["json"] }  # TEAM-158: For device detection HTTP calls
async-trait = "0.1"  # TEAM-161: For DeviceDetector trait implementation
rust-embed = "8.5" # TEAM-293: Embed static files in binary for distribution
mime_guess = "2.0" # TEAM-293: MIME type detection for embedded assets

# CLI
clap = { version = "4", features = ["derive"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Build metadata
shadow-rs = { version = "0.35", default-features = false }

# Time and streaming
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
async-stream = "0.3" # TEAM-288: For async stream! macro in heartbeat_stream
reqwest-eventsource = "0.6" # TEAM-373: SSE client for hive subscriptions

# Error handling
anyhow = "1.0"
tracing = "0.1"  # TEAM-364: For logging in cleanup task

# Internal dependencies
# TEAM-XXX: DELETED lifecycle-ssh - Queen doesn't manage daemons (Keeper does that)
job-server = { path = "../99_shared_crates/job-server" }
observability-narration-core = { path = "../99_shared_crates/narration-core" }
observability-narration-macros = { path = "../99_shared_crates/narration-macros" }  # TEAM-350: For #[with_job_id] macro
stdext = "0.3"  # TEAM-312: Required for n!() macro (function_name!())
once_cell = "1.19"
# TEAM-290: DELETED rbee-config dependency (file-based config deprecated)
queen-rbee-telemetry-registry = { path = "../15_queen_rbee_crates/telemetry-registry" }  # TEAM-374: Telemetry registry (hives + workers)
# TEAM-290: DELETED hive-lifecycle dependency (queen no longer manages hives, rbee-keeper does via SSH)
hive-contract = { path = "../97_contracts/hive-contract" }  # TEAM-284: Hive contract types
rbee-hive-monitor = { path = "../25_rbee_hive_crates/monitor" }  # TEAM-364: Worker telemetry types
worker-contract = { path = "../97_contracts/worker-contract" }  # TEAM-270/284: Worker contract types
queen-rbee-scheduler = { path = "../15_queen_rbee_crates/scheduler" }  # TEAM-275: Job scheduler (stub for M2 Rhai)
# TEAM-284: DELETED daemon-sync, ssh-client, and rbee-heartbeat (replaced by contracts)
operations-contract = { path = "../97_contracts/operations-contract" }  # TEAM-186/284: Operations contract
job-client = { path = "../99_shared_crates/job-client" }  # TEAM-259: Shared job submission client
timeout-enforcer = { path = "../99_shared_crates/timeout-enforcer" }  # TEAM-207: Timeout enforcement
ssh-config-parser = { path = "../99_shared_crates/ssh-config-parser" }  # TEAM-365: SSH config parser for hive discovery
urlencoding = "2.1"  # TEAM-365: URL encoding for queen_url parameter
url = "2.5"  # TEAM-366: URL validation for discovery edge cases

# TODO: Add when registries are migrated
# beehive_registry (for http/routes.rs, http/beehives.rs, etc.)
# worker_registry (for http/routes.rs, http/workers.rs, etc.)
# audit_logging (for http/routes.rs AppState)
# input_validation (for http/beehives.rs, http/inference.rs)

[build-dependencies]
shadow-rs = "0.35"

[dev-dependencies]
# TEAM-158: Test dependencies
tempfile = "3.8"
# TEAM-364: Telemetry testing infrastructure
tokio = { workspace = true, features = ["full", "test-util"] }
serde_json = "1.0"
