# TEAM-135: Created by TEAM-135 (scaffolding)
# TEAM-151: Updated with HTTP server dependencies

[package]
name = "queen-rbee"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "queen-rbee"
path = "src/main.rs"

[dependencies]
# HTTP framework
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-http = { version = "0.6", features = ["cors", "fs"] } # TEAM-288: CORS support for web UI, TEAM-293: Static file serving
reqwest = { version = "0.12", features = ["json"] }  # TEAM-158: For device detection HTTP calls
async-trait = "0.1"  # TEAM-161: For DeviceDetector trait implementation
rust-embed = "8.5" # TEAM-293: Embed static files in binary for distribution
mime_guess = "2.0" # TEAM-293: MIME type detection for embedded assets

# CLI
clap = { version = "4", features = ["derive"] }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time and streaming
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
async-stream = "0.3" # TEAM-288: For async stream! macro in heartbeat_stream

# Error handling
anyhow = "1.0"

# Internal dependencies
daemon-lifecycle = { path = "../99_shared_crates/daemon-lifecycle" }  # TEAM-189: For spawning hive daemons (hive start)
job-server = { path = "../99_shared_crates/job-server" }
observability-narration-core = { path = "../99_shared_crates/narration-core" }
stdext = "0.3"  # TEAM-312: Required for n!() macro (function_name!())
once_cell = "1.19"
# TEAM-290: DELETED rbee-config dependency (file-based config deprecated)
queen-rbee-worker-registry = { path = "../15_queen_rbee_crates/worker-registry" }  # TEAM-188/262: Runtime worker state (RAM)
queen-rbee-hive-registry = { path = "../15_queen_rbee_crates/hive-registry" }  # TEAM-284: Runtime hive state (RAM)
# TEAM-290: DELETED hive-lifecycle dependency (queen no longer manages hives, rbee-keeper does via SSH)
hive-contract = { path = "../97_contracts/hive-contract" }  # TEAM-284: Hive contract types
worker-contract = { path = "../97_contracts/worker-contract" }  # TEAM-270/284: Worker contract types
queen-rbee-scheduler = { path = "../15_queen_rbee_crates/scheduler" }  # TEAM-275: Job scheduler (stub for M2 Rhai)
# TEAM-284: DELETED daemon-sync, ssh-client, and rbee-heartbeat (replaced by contracts)
operations-contract = { path = "../97_contracts/operations-contract" }  # TEAM-186/284: Operations contract
job-client = { path = "../99_shared_crates/job-client" }  # TEAM-259: Shared job submission client
timeout-enforcer = { path = "../99_shared_crates/timeout-enforcer" }  # TEAM-207: Timeout enforcement

# TODO: Add when registries are migrated
# beehive_registry (for http/routes.rs, http/beehives.rs, etc.)
# worker_registry (for http/routes.rs, http/workers.rs, etc.)
# audit_logging (for http/routes.rs AppState)
# input_validation (for http/beehives.rs, http/inference.rs)

[dev-dependencies]
# TEAM-158: Test dependencies
tempfile = "3.8"
