[package]
name = "test-harness-bdd"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["bdd-cucumber"]
bdd-cucumber = []

[dependencies]
regex = { workspace = true }
cucumber = { version = "0.20", features = ["macros"] }
serde_json = "1"
anyhow = { workspace = true }
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
walkdir = { workspace = true }
tempfile = "3"

[dev-dependencies]

[[bin]]
name = "bdd-runner"
path = "src/main.rs"

[[bin]]
name = "bdd-generate-skeletons"
path = "src/bin/bdd-generate-skeletons.rs"
