[package]
name = "test-harness-bdd"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = ["bdd-cucumber"]
bdd-cucumber = []

[dependencies]
regex = { workspace = true }
cucumber = { version = "0.20", features = ["macros"] }
serde_json = "1"
anyhow = { workspace = true }
async-trait = "0.1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
walkdir = { workspace = true }
tempfile = "3"
orchestratord = { path = "../../bin/orchestratord" }
contracts-api-types = { path = "../../contracts/api-types" }
axum = { workspace = true }
http = { workspace = true }
hyper = { workspace = true }
tower = { version = "0.4", features = ["util"] }
futures = { workspace = true }
worker-adapters-llamacpp-http = { path = "../../libs/worker-adapters/llamacpp-http" }
worker-adapters-vllm-http = { path = "../../libs/worker-adapters/vllm-http" }
worker-adapters-tgi-http = { path = "../../libs/worker-adapters/tgi-http" }
worker-adapters-triton = { path = "../../libs/worker-adapters/triton" }
jsonschema = { workspace = true }
contracts-config-schema = { path = "../../contracts/config-schema" }
worker-adapters-adapter-api = { path = "../../libs/worker-adapters/adapter-api" }
pool-managerd = { path = "../../libs/pool-managerd" }
worker-adapters-http-util = { path = "../../libs/worker-adapters/http-util" }
reqwest = { workspace = true }
once_cell = { workspace = true }
auth-min = { path = "../../libs/auth-min" }

[dev-dependencies]

[[bin]]
name = "bdd-runner"
path = "src/main.rs"
