[package]
name = "test-harness-bdd"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
bdd-cucumber = []

[dependencies]
regex = { workspace = true }
cucumber = { version = "0.20", features = ["macros"] }
serde_json = "1"
anyhow = { workspace = true }
async-trait = "0.1"

[dev-dependencies]
walkdir = { workspace = true }
