# Docker Compose for Integration Testing
# Created by: TEAM-106
# Purpose: Run full stack integration tests with real services

version: '3.8'

services:
  # Queen-rbee orchestrator
  queen-rbee:
    build:
      context: ../../
      dockerfile: test-harness/bdd/Dockerfile.queen-rbee
    container_name: llorch-test-queen
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info,queen_rbee=debug
      - LLORCH_QUEEN_PORT=8080
      - LLORCH_HIVE_URL=http://rbee-hive:9200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - llorch-test

  # Rbee-hive worker manager
  rbee-hive:
    build:
      context: ../../
      dockerfile: test-harness/bdd/Dockerfile.rbee-hive
    container_name: llorch-test-hive
    ports:
      - "9200:9200"
    environment:
      - RUST_LOG=info,rbee_hive=debug
      - LLORCH_HIVE_PORT=9200
      - LLORCH_MODELS_DIR=/models
      - LLORCH_DB_PATH=/data/models.db
    volumes:
      - models-data:/models
      - hive-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/v1/health"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - llorch-test

  # Mock worker (for testing without actual inference)
  mock-worker:
    build:
      context: ../../
      dockerfile: test-harness/bdd/Dockerfile.mock-worker
    container_name: llorch-test-worker
    ports:
      - "8001:8001"
    environment:
      - RUST_LOG=info
      - LLORCH_WORKER_PORT=8001
      - LLORCH_WORKER_ID=worker-test-001
      - LLORCH_MODEL_REF=tinyllama-q4
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/v1/ready"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - llorch-test

networks:
  llorch-test:
    driver: bridge

volumes:
  models-data:
  hive-data:
