# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-hive-model-catalog"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "rbee_hive_model_catalog"
path = "src/lib.rs"

[dependencies]
# TEAM-267: Dependencies for filesystem-based model catalog
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"  # For cross-platform cache directory
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"  # For metadata.yaml files

[dev-dependencies]
tempfile = "3.8"  # For isolated test directories
