# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "queen-rbee-ssh-client"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "queen_rbee_ssh_client"
path = "src/lib.rs"

[dependencies]
# TEAM-256: Migrated from ssh2 to russh for better async support and SFTP
russh = "0.44"
russh-keys = "0.44"
russh-sftp = "2.0"
async-trait = "0.1"
tokio = { version = "1", features = ["net", "time", "io-util", "rt"] }
anyhow = "1.0"
observability-narration-core = { path = "../../99_shared_crates/narration-core" }

[dev-dependencies]
# Add dev dependencies as needed
