[package]
name = "worker-registry"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

# Shared worker registry for queen-rbee and rbee-keeper
# Tracks workers across pool nodes using SQLite

[dependencies]
anyhow = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
uuid = { workspace = true, features = ["v4"] }
