# TEAM-135: Created for happy flow requirements

[package]
name = "rbee-hive-worker-catalog"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "rbee_hive_worker_catalog"
path = "src/lib.rs"

[dependencies]
tokio = { workspace = true }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = "3.0"
