# TEAM-273: Worker catalog using artifact-catalog abstraction

[package]
name = "rbee-hive-worker-catalog"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "rbee_hive_worker_catalog"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
chrono = { version = "0.4", features = ["serde"] }

# Shared catalog abstraction
rbee-hive-artifact-catalog = { path = "../artifact-catalog" }

[dev-dependencies]
tempfile = "3.8"
