# TEAM-135: Created for happy flow requirements

[package]
name = "queen-rbee-health"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "queen_rbee_health"
path = "src/lib.rs"

[dependencies]
# HTTP framework
axum = { workspace = true }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
# Add dev dependencies as needed
