openapi: 3.0.3
info:
  title: rbee Control Plane API (v2)
  version: 2.0.0
  description: |
    Pool lifecycle and provisioning controls (drain, reload, purge) and worker registration.
servers:
  - url: /
paths:
  /v2/pools/{id}/drain:
    post:
      operationId: drainPoolV2
      summary: Initiate pool drain with deadline
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
        - $ref: '#/components/parameters/XCorrelationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DrainRequestV2'
      responses:
        '202':
          description: Accepted
          headers:
            X-Correlation-Id:
              schema: { type: string }
  /v2/pools/{id}/reload:
    post:
      operationId: reloadPoolV2
      summary: Reload a pool with a new model reference (may trigger fetch)
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
        - $ref: '#/components/parameters/XCorrelationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReloadRequestV2'
      responses:
        '202':
          description: Accepted
          headers:
            X-Correlation-Id:
              schema: { type: string }
  /v2/pools/{id}/purge:
    post:
      operationId: purgePoolV2
      summary: Purge engine and/or model artifacts for a pool (retesting convenience)
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
        - $ref: '#/components/parameters/XCorrelationId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurgeRequestV2'
      responses:
        '202':
          description: Accepted
          headers:
            X-Correlation-Id:
              schema: { type: string }
  /v2/pools/{id}/health:
    get:
      operationId: getPoolHealthV2
      summary: Pool health and readiness
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: string }
        - $ref: '#/components/parameters/XCorrelationId'
      responses:
        '200':
          description: Health summary
          headers:
            X-Correlation-Id:
              schema: { type: string }
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolHealthV2'
  /v2/workers/register:
    post:
      operationId: registerWorkerV2
      summary: Register a worker adapter instance with a pool/replica (dev only)
      parameters:
        - $ref: '#/components/parameters/XCorrelationId'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                pool_id: { type: string }
                replica_id: { type: string }
      responses:
        '200':
          description: OK
          headers:
            X-Correlation-Id:
              schema: { type: string }
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok: { type: boolean }
                  identity: { type: string }
                  pool_id: { type: string }
                  replica_id: { type: string }

components:
  parameters:
    XCorrelationId:
      name: X-Correlation-Id
      in: header
      required: false
      schema: { type: string }
      description: Optional request correlation ID; echoed back in responses.
  schemas:
    DrainRequestV2:
      type: object
      required: [deadline_ms]
      properties:
        deadline_ms: { type: integer, format: int64 }
    ReloadRequestV2:
      type: object
      required: [new_model_ref]
      properties:
        new_model_ref: { type: string }
    PurgeRequestV2:
      type: object
      properties:
        purge_engine: { type: boolean, default: false }
        purge_models: { type: array, items: { type: string } }
        drain_first: { type: boolean, default: true }
        delete_cache_dirs: { type: boolean, default: false }
        force: { type: boolean, default: false }
    PoolHealthV2:
      type: object
      properties:
        live: { type: boolean }
        ready: { type: boolean }
        draining: { type: boolean }
        metrics: { type: object, additionalProperties: true }
