[package]
name = "model-loader"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true
input-validation = { path = "../../shared-crates/input-validation" }
tokio = { workspace = true, features = ["sync", "rt"] }
metrics = "0.21"

# Observability
observability-narration-core = { path = "../../shared-crates/narration-core" }
audit-logging = { path = "../../shared-crates/audit-logging" }
chrono = { workspace = true }

[dev-dependencies]
proptest.workspace = true
tempfile = "3.8"
