[package]
name = "model-loader"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
sha2.workspace = true
input-validation = { path = "../../shared-crates/input-validation" }

[dev-dependencies]
proptest.workspace = true
tempfile = "3.8"
