Feature: Proof bundle artifacts carry autogenerated headers and metadata
  # Traceability: PB-1012; PBV-2009, PBV-2003
  As a test author
  I want proof-bundle to enforce headers and metadata automatically
  So that all artifacts are compliant with the spec

  Scenario: Markdown header is automatically prepended
    Given a proof bundle of type "integration" with run id "BDD-RUN-1"
    When I write markdown "test_report.md" body "# OK"
    Then file "test_report.md" first line equals "# AUTOGENERATED: Proof Bundle"

  Scenario: JSON writes a sibling .meta file
    Given a proof bundle of type "integration" with run id "BDD-RUN-2"
    When I write json "run_config" value {"ok": true}
    Then file exists "run_config.json"
    And file exists "run_config.json.meta"

  Scenario: NDJSON first record is a metadata record
    Given a proof bundle of type "integration" with run id "BDD-RUN-3"
    When I append ndjson "stream" value {"event":"started"}
    Then first line of "stream.ndjson" contains "\"_meta\":\"proof_bundle\""

  Scenario: Markdown explicit with-header API also yields header
    Given a proof bundle of type "integration" with run id "BDD-RUN-4"
    When I write markdown with header "notes.md" body "- line"
    Then file "notes.md" first line equals "# AUTOGENERATED: Proof Bundle"

  Scenario: Ensure NDJSON meta is written only once and file is newline-terminated
    Given a proof bundle of type "integration" with run id "BDD-RUN-5"
    When I ensure ndjson meta "stream2"
    And I append ndjson "stream2" value {"event":"started"}
    And I ensure ndjson meta "stream2"
    Then first line of "stream2.ndjson" contains "\"_meta\":\"proof_bundle\""
    And file "stream2.ndjson" has exactly 2 lines
    And file "stream2.ndjson" ends with a newline

  Scenario: NDJSON appending adds one record per call
    Given a proof bundle of type "integration" with run id "BDD-RUN-6"
    When I append ndjson "stream3" value {"event":"first"}
    And I append ndjson "stream3" value {"event":"second"}
    Then file "stream3.ndjson" has exactly 3 lines
    And line 3 of "stream3.ndjson" equals "{\"event\":\"second\"}"

  Scenario: Markdown without extension still gets header (PB-1004, PB-1012)
    Given a proof bundle of type "integration" with run id "BDD-RUN-7"
    When I write markdown "plain_report" body "# OK"
    Then file "plain_report" first line equals "# AUTOGENERATED: Proof Bundle"
