Feature: Writers and parent directory behavior
  Verify PB-1004, PB-1005, PB-1006: formats, minimal API, parent directory creation, overwrites.

  Background:
    Given a proof bundle of type "integration" with run id "BDD-WRITERS-1"

  Scenario: Ensure dir creates nested subdirectories
    When I ensure dir "logs/sub"
    Then dir exists "logs/sub"

  Scenario: Markdown write enforces header and overwrites
    When I overwrite markdown "logs/sub/report.md" with body "# First report"
    Then file "logs/sub/report.md" first line equals "# AUTOGENERATED: Proof Bundle"
    And second line of "logs/sub/report.md" equals "# First report"
    When I overwrite markdown "logs/sub/report.md" with body "# Second report"
    Then second line of "logs/sub/report.md" equals "# Second report"

  Scenario: JSON write ensures .json extension and meta sibling
    When I write json file base "config/run" value {"ok": true}
    Then file exists "config/run.json"
    And file exists "config/run.json.meta"
    And json file "config/run.json" has field "ok" equals "true"
    And file "config/run.json" has at least 2 lines

  Scenario: JSON with meta helper also creates meta
    When I write json with meta base "config/run2" value {"ok": "yes"}
    Then file exists "config/run2.json"
    And file exists "config/run2.json.meta"

  Scenario: JSON write overwrites existing file
    When I write json file base "config/overwrite" value {"version": 1}
    Then json file "config/overwrite.json" has field "version" equals "1"
    When I write json file base "config/overwrite" value {"version": 2}
    Then json file "config/overwrite.json" has field "version" equals "2"

  Scenario: Write meta sibling explicitly for a JSON file
    When I write meta sibling for "config/custom.json"
    Then file exists "config/custom.json.meta"

  Scenario: NDJSON append to nested path creates parents and writes meta
    When I append ndjson "logs/deep/stream_nested" value {"e":1}
    Then first line of "logs/deep/stream_nested.ndjson" contains "\"_meta\":\"proof_bundle\""
    And file "logs/deep/stream_nested.ndjson" has at least 2 lines

  Scenario: Markdown with .txt extension still gets header
    When I overwrite markdown "logs/note.txt" with body "hello"
    Then file "logs/note.txt" first line equals "# AUTOGENERATED: Proof Bundle"
