# TEAM-135: Created by TEAM-135 (scaffolding)

[package]
name = "rbee-keeper-queen-lifecycle"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "rbee_keeper_queen_lifecycle"
path = "src/lib.rs"

[dependencies]
# Shared lifecycle management
daemon-lifecycle = { path = "../../99_shared_crates/daemon-lifecycle" }

# Narration for observability
observability-narration-core = { path = "../../99_shared_crates/narration-core" }

# Async runtime
tokio = { version = "1", features = ["time"] }

# HTTP client for health checks
reqwest = { version = "0.11", features = ["json"] }

# Error handling
anyhow = "1.0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
