# TEAM-259: Created by TEAM-259 (extracted from rbee-keeper)
# Purpose: Queen-rbee lifecycle management

[package]
name = "queen-lifecycle"
version = "0.1.0"
edition = "2021"
authors = ["TEAM-259"]
description = "Queen-rbee lifecycle management for rbee-keeper"
license = "GPL-3.0-or-later"

[dependencies]
# Core dependencies
anyhow = "1.0"
tokio = { version = "1", features = ["time"] }
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0" # TEAM-292: For parsing queen info response

# Shared crates
daemon-lifecycle = { path = "../../99_shared_crates/daemon-lifecycle" }
daemon-contract = { path = "../../97_contracts/daemon-contract" }  # TEAM-315: Generic daemon handle
observability-narration-core = { path = "../../99_shared_crates/narration-core" }
# TEAM-290: DELETED rbee-config dependency (file-based config deprecated)
timeout-enforcer = { path = "../../99_shared_crates/timeout-enforcer" }
stdext = "0.3"  # TEAM-312: Required for n!() macro (function_name!())

[lints]
workspace = true
