[package]
name = "streaming"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tokio = { workspace = true }
futures.workspace = true
tracing.workspace = true
serde = { workspace = true }
serde_json.workspace = true
