# TEAM-193: Created auto-update crate for dependency-aware binary rebuilding
# Purpose: Shared auto-update logic with full Cargo.toml dependency tracking

[package]
name = "auto-update"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
# Cargo.toml parsing
cargo_toml = "0.20"

# File system operations
walkdir = "2.4"

# Error handling
anyhow = "1.0"

# Observability
observability-narration-core = { path = "../narration-core" }

[dev-dependencies]
tempfile = "3.8"
