[package]
name = "jwt-guardian"
version = "0.0.0"
edition = "2021"
publish = false
license = "GPL-3.0-or-later"
autobenches = false
autotests = false
autodocs = false

[lib]
name = "jwt_guardian"
path = "src/lib.rs"

[dependencies]
# Core dependencies
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

# JWT handling
jsonwebtoken = "9"
base64 = "0.22"

# Cryptography
sha2 = { workspace = true }

# Time handling
chrono = "0.4"

# Optional: Redis for revocation lists
redis = { version = "0.27", optional = true, features = ["tokio-comp"] }
tokio = { workspace = true, optional = true }

[features]
default = []
revocation = ["redis", "tokio"]

[dev-dependencies]
tokio = { workspace = true }
