[package]
name = "job-timeout"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
tokio = { workspace = true }
