[package]
name = "pool-ctl"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[[bin]]
name = "llorch-pool"
path = "src/main.rs"

[dependencies]
pool-core = { path = "../shared-crates/pool-core" }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
colored = "2.0"
serde_json = "1.0"
hostname = "0.4"
