[package]
name = "input-validation"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
proptest = "1.0"
