# TEAM-284: Hive contract types and API specification
#
# This crate defines the contract that ALL hive implementations must follow.
# Mirrors worker-contract but for hives.

[package]
name = "hive-contract"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[lib]
name = "hive_contract"
path = "src/lib.rs"

[dependencies]
# Shared contract types
shared-contract = { path = "../shared-contract" }

# TEAM-285: Generic heartbeat registry
heartbeat-registry = { path = "../../99_shared_crates/heartbeat-registry" }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
# Testing
