# TEAM-294: SSH config parser for rbee-keeper
# TEAM-314: Added SSH client for remote command execution
# Parses ~/.ssh/config to discover available hives
# Provides SSH client for remote operations

[package]
name = "ssh-config"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
# TEAM-314: Added for SSH client
tokio = { version = "1.0", features = ["process"] }
observability-narration-core = { path = "../../99_shared_crates/narration-core" }
stdext = "0.3"  # Required for n!() macro (function_name!())
# TEAM-315: Use SSH types from contract
ssh-contract = { path = "../../97_contracts/ssh-contract" }

[dev-dependencies]
tempfile = "3.8"

[lints]
workspace = true
